name: flutter_folio
description: Create and share beautiful Scrapbooks using Photos, Text and Stickers!
publish_to: 'none'
version: 1.1.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^2.0.0
  #todo: land this patch
  auto_size_text:
    git:
      url: git://github.com/gskinnerTeam/auto_size_text.git
      ref: 8800276218b053265ffc796a24e84820bebaaeac
  bitsdojo_window: ^0.1.0
  cached_network_image: ^3.0.0
  cloudinary_public: ^0.8.0
  darq: ^1.0.0-dev.3
  dotted_border: ^2.0.0-nullsafety.0
  email_validator: ^2.0.1
  enum_to_string: ^2.0.0-nullsafety.1
  flutter_lorem: ^2.0.0
  flextras: ^0.0.1
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_linux: ^0.0.2
  file_selector_web: ^0.8.1
  flutter_svg: ^0.21.0-nullsafety.0
  image_picker: ^0.7.2
  image_size_getter: ^1.0.0
  multi_image_picker: ^4.8.00
  path_provider: ^2.0.1
  provider: ^5.0.0
  random_color: ^1.0.6-nullsafety
  sized_context: 1.0.0-nullsafety
  shared_preferences: ^2.0.4
  share: ^2.0.1
  system_info: ^1.0.0
  statsfl: 2.0.1-nullsafety
  timeago: ^3.0.2
  universal_platform: ^1.0.0-nullsafety
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  visibility_detector: ^0.2.0-nullsafety.1
  desktop_window: ^0.4.0

  # FIREBASE
  firedart: ^0.9.0+1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1

  # Rich text editor
  super_editor:
    git:
      url: git://github.com/superlistapp/super_editor.git
      ref: 7438b7e3508b7b16d1e63f282d311f9796ca77c4
      path: super_editor


dev_dependencies:
  # sample build cmd
  # flutter pub run build_runner build --delete-conflicting-outputs
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.1
  freezed_annotation: ^0.14.1
  json_serializable:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: source-assets/app-flutter-folio.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/emoji/
    - assets/images/logos/
    - assets/images/landing_page/

  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces_72pt-SemiBold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/scraps/AlfaSlabOne-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/scraps/Amiri-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/scraps/Caveat-Medium.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/scraps/Lato-Regular.ttf
    - family: Mali
      fonts:
        - asset: assets/fonts/scraps/Mali-Medium.ttf
    - family: PathwayGothicOne
      fonts:
        - asset: assets/fonts/scraps/PathwayGothicOne-Regular.ttf
